name: doctor_finder
description: A doctor finder application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.1
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
